language: java

jdk:
  - oraclejdk8

services:
  - docker

env:
  global:
    - OPENSHIFT_REGISTRY="openshift-registry.adorsys.de"
    - OPENSHIFT_NAMESPACE_BANKING_GATEWAY_DEV="banking-gateway-dev"
    - HARBOR_REGISTRY="harbor.adorsys.de"
    - HARBOR_NAMESPACE_BANKING_GATEWAY_DEV="teambank-banking-gateway"

git:
  submodules: false

cache:
  directories:
    - .autoconf
    - $HOME/.m2

install:
  - mvn --settings .travis/settings.xml clean install -DskipTests -Dmaven.javadoc.skip=true -B -V

script:
  - /bin/bash .travis/build.sh

before_deploy:
  - echo $GPG_SECRET_KEY | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

deploy:
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      tags: true
      # matches: vX.Y.Z, vX.Y.Z-A, vX.Y.Z-RCA, vX.Y.Z-A-B.C.D, vX.Y.Z-A-B.C.D-E, vX.Y.Z-RCA-B.C.D-E
      condition: "$TRAVIS_TAG =~ ^v([[:digit:]]+\\.)+[[:digit:]]+(-(RC)?[[:digit:]]+)?(-([[:digit:]]+\\.)+[[:digit:]]+(-[[:digit:]]+)?)?$"
  -
    skip_cleanup: true
    provider: script
    script: /bin/bash .travis/deploy.sh
    on:
      branch: develop
  # Deploy to opehsift banking-gateway-dev
  - provider: script
    skip_cleanup: true
    script: env TAG=latest OPENSHIFT_NAMESPACE=$OPENSHIFT_NAMESPACE_BANKING_GATEWAY_DEV  OPENSHIFT_USER=$OPENSHIFT_BANKING_GATEWAY_DEV_USER OPENSHIFT_TOKEN=$OPENSHIFT_BANKING_GATEWAY_TOKEN .travis/deploy_openshift.sh
    on:
      branch: KOA_add_deployment_to_openshift
  # Deploy to harbor banking-gateway
  - provider: script
    skip_cleanup: true
    script:  env HARBOR_NAMESPACE=$HARBOR_NAMESPACE_BANKING_GATEWAY_DEV HARBOR_USER=$HARBOR_BANKING_GATEWAY_USER HARBOR_TOKEN=$HARBOR_BANKING_GATEWAY_TOKEN .travis/deploy_harbor.sh
    on:
      branch: KOA_add_deployment_to_openshift


