spring:
  application:
    name: multibanking-service
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson.default-property-inclusion: non_null

server:
  port: 8088
  use-forward-headers: true

management:
  context-path: /management
  security:
    enabled: false

info:
  project:
    artifact: #project.artifactId#
    name: #project.name#
    description: #project.description#
    version: #project.version#
    timestamp: #maven.build-timestamp#
    scmBranch: #scmBranch#
    buildnumber: #buildNumber#

defaultBankApi: HBCI

sts:
  audience_name: Multibanking
  secret_claim_property_key: user-secret
  keymanagement.keystore.password: FEDCBA9876543210
  keymanagement.keystore.name: multibanking-keystore
  keymanagement.keystore.alias_prefix: multibanking-
  keymanagement.keystore.type: UBER
  keymanagement.keystore.keys.encKeyPairs.initialCount: 5
  keymanagement.keystore.keys.encKeyPairs.algo: RSA
  keymanagement.keystore.keys.encKeyPairs.sigAlgo: SHA256withRSA
  keymanagement.keystore.keys.encKeyPairs.size: 2048
  keymanagement.keystore.keys.encKeyPairs.name: 'STS Multibanking'
  keymanagement.keystore.keys.encKeyPairs.validityInterval: 3600000
  keymanagement.keystore.keys.encKeyPairs.legacyInterval: 86400000
  keymanagement.keystore.keys.signKeyPairs.initialCount: 5
  keymanagement.keystore.keys.signKeyPairs.algo: RSA
  keymanagement.keystore.keys.signKeyPairs.sigAlgo: SHA256withRSA
  keymanagement.keystore.keys.signKeyPairs.size: 2048
  keymanagement.keystore.keys.signKeyPairs.name: 'STS Multibanking'
  keymanagement.keystore.keys.signKeyPairs.validityInterval: 3600000
  keymanagement.keystore.keys.signKeyPairs.legacyInterval: 86400000
  keymanagement.keystore.keys.secretKeys.initialCount: 5
  keymanagement.keystore.keys.secretKeys.algo: AES
  keymanagement.keystore.keys.secretKeys.size: 256
  keymanagement.keystore.keys.secretKeys.validityInterval: 3600000
  keymanagement.keystore.keys.secretKeys.legacyInterval: 86400000
  keymanagement.rotation.secretKeys.enabled: false
  keymanagement.rotation.signKeyPairs.enabled: false
  keymanagement.rotation.encKeyPairs.enabled: false

#bankinggateway.b2c.url: http://localhost:8084
bankinggateway.b2c.url: https://dev-bankinggateway-b2c.cloud.adorsys.de
bankinggateway.adapter.url: https://dev-bankinggateway-adapter.cloud.adorsys.de

pkcs12.keyStore.url: classpath:/example_eidas.p12
pkcs12.keyStore.password:

ing:
  url: https://api.sandbox.ing.com
  qwac:
    alias: example_eidas_client_tls
  qseal:
    alias: example_eidas_client_signing

bank.import.file: /Users/alexg/Downloads/multibanking/catalogue/banks/bank-catalogue.yml

---

spring:
  profiles: dev-mongo
  profiles.include:
    - swagger
    - mongo
    - sts-enable
    - mongo-persistence
    - sca-persistence-mongodb
    - smartanalytics-embedded
    - bankinggateway-b2c-embedded
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

db_secret: 1234567890123456

mongo.properties.url: classpath:/mongo.properties
swagger.login.url: http://keycloak:8080/auth/realms/multibanking/protocol/openid-connect/auth

idp:
  baseUrl: http://keycloak:8080
  realm: multibanking

sts:
  authservers:
    - name: keycloak
      issUrl: ${idp.baseUrl}/auth/realms/${idp.realm}
      jwksUrl: ${idp.baseUrl}/auth/realms/${idp.realm}/protocol/openid-connect/certs

---

spring:
  profiles: dev-jpa
  profiles.include:
    - swagger
    - jpa
    - sts-enable
    - smartanalytics-remote
  datasource:
    url: jdbc:postgresql://localhost:5432/mbs
    username: mbs
    password: mbs
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  liquibase:
    enabled: false
    change-log: classpath:/liquibase/changelog-master.xml

swagger.login.url: http://keycloak:8080/auth/realms/multibanking/protocol/openid-connect/auth

idp:
  baseUrl: http://keycloak:8080
  realm: multibanking

sts:
  authservers:
    - name: keycloak
      issUrl: ${idp.baseUrl}/auth/realms/${idp.realm}
      jwksUrl: ${idp.baseUrl}/auth/realms/${idp.realm}/protocol/openid-connect/certs

---

spring:
  profiles: dev-sts-disabled
  profiles.include:
    - swagger
    - mongo
    - mongo-persistence
    - smartanalytics-embedded

db_secret: 1234567890123456
mongo.properties.url: classpath:/mongo.properties

---

spring:
  profiles: prod
  profiles.include:
    - swagger
    - mongo
    - sts-enable
    - mongo-persistence
    - smartanalytics-embedded
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---

spring:
  profiles: prod-smartanalytics-remote
  profiles.include:
    - swagger
    - mongo
    - sts-enable
    - mongo-persistence
    - smartanalytics-remote
  autoconfigure.exclude:
    - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---

spring:
  profiles: prod-sts-disabled
  profiles.include:
    - swagger
    - mongo
    - mongo-persistence
    - smartanalytics-embedded

